# Auto-generate PPT and export to PDF for CommandDispatcher commands
import ast
from datetime import date
from pptx import Presentation
from pptx.util import Pt, Inches
import os
import comtypes.client
import textwrap

EXPORT_TO_PDF = False
FONT_SIZE = 12
file_path = r"c:\\WC\\HotSystem\\CommandDispatcher.py"
out_pptx = "CommandDispatcher_Commands.pptx"
out_pdf = "CommandDispatcher_Commands.pdf"

def wrap_lines(lines, max_chars=70):
    wrapped = []
    for line in lines:
        wrapped.extend(textwrap.wrap(line, width=max_chars, break_long_words=False, break_on_hyphens=False))
    return wrapped


# 1. Load Python source
with open(file_path, 'r', encoding='utf-8') as f:
    source_code = f.read()

# 2. Parse AST
class_node = next(
    (node for node in ast.parse(source_code).body if isinstance(node, ast.ClassDef) and node.name == "CommandDispatcher"),
    None
)
if not class_node:
    raise ValueError("CommandDispatcher class not found.")

# 3. Extract handlers
handlers_mapping = {}
for node in class_node.body:
    if isinstance(node, ast.FunctionDef) and node.name == "__init__":
        for sub in node.body:
            if isinstance(sub, ast.Assign):
                for target in sub.targets:
                    if (isinstance(target, ast.Attribute) and isinstance(sub.value, ast.Dict)
                            and target.attr == "handlers"):
                        for key_node, val_node in zip(sub.value.keys, sub.value.values):
                            if isinstance(key_node, ast.Constant) and isinstance(key_node.value, str):
                                cmd_name = key_node.value
                                handler_name = None
                                if isinstance(val_node, ast.Attribute):
                                    if isinstance(val_node.value, ast.Name) and val_node.value.id == "self":
                                        handler_name = val_node.attr
                                elif isinstance(val_node, ast.Lambda):
                                    if isinstance(val_node.body, ast.Call):
                                        func = val_node.body.func
                                        if isinstance(func, ast.Attribute):
                                            handler_name = func.attr
                                handlers_mapping[cmd_name] = handler_name

# 4. Extract docstrings
func_docs = {node.name: ast.get_docstring(node, clean=True) for node in class_node.body if isinstance(node, ast.FunctionDef)}

# 5. Start PowerPoint
prs = Presentation()
layout = prs.slide_layouts[1]  # Title and Content
command_slide_refs = {}

# Title Slide
title_slide = prs.slides.add_slide(prs.slide_layouts[0])
title_slide.shapes.title.text = "Auto-Generated Help for Commands in Console GUI"
title_slide.placeholders[1].text = f"This file was generated by the Python file 'generate_help_ppt.py'\nDate: {date.today()}"

# Index Slide
index_slide = prs.slides.add_slide(prs.slide_layouts[5])
index_slide.shapes.title.text = "Command Index"

# Generate command slides
commands_sorted = sorted(handlers_mapping.keys())
for cmd in commands_sorted:
    handler = handlers_mapping[cmd]
    doc = func_docs.get(handler)
    lines = [line.strip() for line in doc.strip().splitlines() if line.strip()] if doc else []
    lines = wrap_lines(lines)

    is_long = len(lines) > 10
    slide = prs.slides.add_slide(prs.slide_layouts[5] if is_long else layout)
    slide.shapes.title.text = cmd

    if is_long:
        col_gap = Inches(0.3)
        col_width = Inches(5)
        height = prs.slide_height - Inches(1.5)

        left_col = Inches(0.1)
        right_col = left_col + col_width + col_gap

        top = Inches(1.0)
        mid = len(lines) // 2
        left_lines = lines[:mid]
        right_lines = lines[mid:]
        left_box = slide.shapes.add_textbox(left_col, top, col_width, height).text_frame
        right_box = slide.shapes.add_textbox(right_col, top, col_width, height).text_frame
        for box, chunk in [(left_box, left_lines), (right_box, right_lines)]:
            for line in chunk:
                p = box.add_paragraph()
                p.text = line
                for r in p.runs:
                    r.font.size = Pt(FONT_SIZE)
    else:
        tf = slide.placeholders[1].text_frame
        tf.clear()
        for line in lines:
            p = tf.add_paragraph()
            p.text = line
            for r in p.runs:
                r.font.size = Pt(FONT_SIZE)

    tf = slide.placeholders[1].text_frame if not is_long and len(slide.placeholders) > 1 else right_box
    p = tf.add_paragraph()
    p.text = "Usage Example:"
    usage = f"{cmd} [arg]" if cmd not in {"exit", "help", "quit"} else cmd
    p = tf.add_paragraph()
    p.text = usage
    for r in p.runs:
        r.font.size = Pt(FONT_SIZE)

    command_slide_refs[cmd] = slide

# Populate index
num_columns = 5
col_width = prs.slide_width / num_columns - Inches(0.2)
row_height = Inches(0.4)
margin_top = Inches(1.2)
margin_left = Inches(0.2)

for idx, cmd in enumerate(commands_sorted):
    col = idx % num_columns
    row = idx // num_columns
    left = margin_left + col * (col_width + Inches(0.2))
    top = margin_top + row * row_height
    width = col_width
    height = row_height
    box = index_slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    run = tf.paragraphs[0].add_run()
    run.text = cmd
    run.font.size = Pt(FONT_SIZE)
    run.hyperlink.target_slide = command_slide_refs[cmd]

# Add history slide
slide = prs.slides.add_slide(layout)
slide.shapes.title.text = "Command History Access"
tf = slide.placeholders[1].text_frame
tf.clear()
for line in [
    "1 - Re-run the most recent command",
    "2 - Re-run the 2nd most recent command",
    "3 - Re-run the 3rd most recent command",
    "1? - Show the most recent command without executing",
    "2? - Show the 2nd most recent command without executing",
    "3? - Show the 3rd most recent command without executing",
    "? - List all recent command history"
]:
    p = tf.add_paragraph()
    p.text = line
    for r in p.runs:
        r.font.size = Pt(FONT_SIZE)

# Save PPTX
prs.save(out_pptx)

# Export to PDF if enabled
if EXPORT_TO_PDF:
    powerpoint = comtypes.client.CreateObject("Powerpoint.Application")
    powerpoint.Visible = 1
    ppt = powerpoint.Presentations.Open(os.path.abspath(out_pptx), WithWindow=False)
    ppt.SaveAs(os.path.abspath(out_pdf), FileFormat=32)  # 32 = PDF
    ppt.Close()
    powerpoint.Quit()