from enum import Enum


class AttoJSONMethods(Enum):
    """
    Holds the strings for the JSON commands to the attocube.
    Need to verify each command is valid. Was generated by GPT from the manual, and include hallucinations
    """
    # Control - Get Methods
    GET_ACTOR_NAME = "com.attocube.amc.control.getActorName"
    GET_ACTOR_PARAMETERS_ACTOR_NAME = "com.attocube.amc.control.getActorParametersActorName"
    GET_ACTOR_SENSITIVITY = "com.attocube.amc.control.getActorSensitivity"
    GET_ACTOR_TYPE = "com.attocube.amc.control.getActorType"
    GET_AUTO_MEASURE = "com.attocube.amc.control.getAutoMeasure"
    GET_CONTROL_AMPLITUDE = "com.attocube.amc.control.getControlAmplitude"
    GET_CONTROL_AUTO_RESET = "com.attocube.amc.control.getControlAutoReset"
    GET_CONTROL_FIX_OUTPUT_VOLTAGE = "com.attocube.amc.control.getControlFixOutputVoltage"
    GET_CONTROL_FREQUENCY = "com.attocube.amc.control.getControlFrequency"
    GET_CONTROL_MOVE = "com.attocube.amc.control.getControlMove"
    GET_CONTROL_OUTPUT = "com.attocube.amc.control.getControlOutput"
    GET_CONTROL_REFERENCE_AUTO_UPDATE = "com.attocube.amc.control.getControlReferenceAutoUpdate"
    GET_CONTROL_TARGET_RANGE = "com.attocube.amc.control.getControlTargetRange"
    GET_CROSSTALK_THRESHOLD = "com.attocube.amc.control.getCrosstalkThreshold"
    GET_CURRENT_OUTPUT_VOLTAGE = "com.attocube.amc.control.getCurrentOutputVoltage"
    GET_EXTERNAL_SENSOR = "com.attocube.amc.control.getExternalSensor"
    GET_FINE_POSITIONING_RANGE = "com.attocube.amc.control.getFinePositioningRange"
    GET_FINE_POSITIONING_SLEW_RATE = "com.attocube.amc.control.getFinePositioningSlewRate"
    GET_MOTION_CONTROL_THRESHOLD = "com.attocube.amc.control.getMotionControlThreshold"
    GET_POSITIONS_AND_VOLTAGES = "com.attocube.amc.control.getPositionsAndVoltages"
    GET_REFERENCE_POSITION = "com.attocube.amc.control.getReferencePosition"
    GET_SENSOR_DIRECTION = "com.attocube.amc.control.getSensorDirection"
    GET_SENSOR_ENABLED = "com.attocube.amc.control.getSensorEnabled"
    GET_STATUS_MOVING_ALL_AXES = "com.attocube.amc.control.getStatusMovingAllAxes"

    # Control - Set Methods
    SET_ACTOR_PARAMETERS_BY_NAME = "com.attocube.amc.control.setActorParametersByName"
    SET_ACTOR_PARAMETERS_JSON = "com.attocube.amc.control.setActorParametersJson"
    SET_ACTOR_SENSITIVITY = "com.attocube.amc.control.setActorSensitivity"
    SET_AUTO_MEASURE = "com.attocube.amc.control.setAutoMeasure"
    SET_CONTROL_AMPLITUDE = "com.attocube.amc.control.setControlAmplitude"
    SET_CONTROL_AUTO_RESET = "com.attocube.amc.control.setControlAutoReset"
    SET_CONTROL_FIX_OUTPUT_VOLTAGE = "com.attocube.amc.control.setControlFixOutputVoltage"
    SET_CONTROL_FREQUENCY = "com.attocube.amc.control.setControlFrequency"
    SET_CONTROL_MOVE = "com.attocube.amc.control.setControlMove"
    SET_CONTROL_OUTPUT = "com.attocube.amc.control.setControlOutput"
    SET_CONTROL_REFERENCE_AUTO_UPDATE = "com.attocube.amc.control.setControlReferenceAutoUpdate"
    SET_CONTROL_TARGET_RANGE = "com.attocube.amc.control.setControlTargetRange"
    SET_CROSSTALK_THRESHOLD = "com.attocube.amc.control.setCrosstalkThreshold"
    SET_EXTERNAL_SENSOR = "com.attocube.amc.control.setExternalSensor"
    SET_FINE_POSITIONING_RANGE = "com.attocube.amc.control.setFinePositioningRange"
    SET_FINE_POSITIONING_SLEW_RATE = "com.attocube.amc.control.setFinePositioningSlewRate"
    SET_MOTION_CONTROL_THRESHOLD = "com.attocube.amc.control.setMotionControlThreshold"
    SET_RESET = "com.attocube.amc.control.setReset"
    SET_SENSOR_DIRECTION = "com.attocube.amc.control.setSensorDirection"

    # Move - Get Methods
    GET_POSITION = "com.attocube.amc.move.getPosition"
    GET_TARGET_POSITION = "com.attocube.amc.move.getControlTargetPosition"

    # Move - Set Methods
    MOVE_ABSOLUTE = "com.attocube.amc.move.setControlTargetPosition"
    MOVE_RELATIVE = "com.attocube.amc.move.moveRelative"
    MOVE_TO_REFERENCE = "com.attocube.amc.move.moveReference"
    STOP_MOVEMENT = "com.attocube.amc.move.stopMovement"

    # Access and System Methods
    GET_LOCK_STATUS = "getLockStatus"
    GRANT_ACCESS = "grantAccess"
    LOCK = "lock"
    UNLOCK = "unlock"

    # Amcids Methods
    GET_LOWER_SOFT_LIMIT = "com.attocube.amc.amcids.getLowerSoftLimit"
    GET_SOFT_LIMIT_ENABLED = "com.attocube.amc.amcids.getSoftLimitEnabled"
    GET_SOFT_LIMIT_REACHED = "com.attocube.amc.amcids.getSoftLimitReached"
    GET_UPPER_SOFT_LIMIT = "com.attocube.amc.amcids.getUpperSoftLimit"
    RESET_IDS_AXIS = "com.attocube.amc.amcids.resetIdsAxis"
    SET_LOWER_SOFT_LIMIT = "com.attocube.amc.amcids.setLowerSoftLimit"
    SET_SOFT_LIMIT_ENABLED = "com.attocube.amc.amcids.setSoftLimitEnabled"
    SET_UPPER_SOFT_LIMIT = "com.attocube.amc.amcids.setUpperSoftLimit"

    # Diagnostic Methods
    GET_DIAGNOSTIC_DATA = "com.attocube.amc.diagnostic.getDiagnosticData"
    GET_ERROR_HISTORY = "com.attocube.amc.diagnostic.getErrorHistory"
    CLEAR_ERROR_HISTORY = "com.attocube.amc.diagnostic.clearErrorHistory"

    # Res Methods
    RESET_AXIS = "com.attocube.amc.res.resetAxis"

    # Rotcomp Methods
    GET_ROT_COMP = "com.attocube.amc.rotcomp.getRotComp"
    SET_ROT_COMP = "com.attocube.amc.rotcomp.setRotComp"

    # System Service Methods
    # REBOOT_SYSTEM = "com.attocube.system.rebootSystem"
    GET_FIRMWARE_VERSION = "com.attocube.system.getFirmwareVersion"

    # Network Methods
    DISCOVER_DEVICES = "com.attocube.network.discoverDevices"
    SET_NETWORK_CONFIGURATION = "com.attocube.network.setNetworkConfiguration"
    GET_NETWORK_CONFIGURATION = "com.attocube.network.getNetworkConfiguration"

    # Temperature Methods (if applicable)
    SET_TEMPERATURE = "com.attocube.amc.temperature.setTemperature"
    GET_TEMPERATURE = "com.attocube.amc.temperature.getTemperature"
    STABILIZE_TEMPERATURE = "com.attocube.amc.temperature.stabilizeTemperature"

    # Miscellaneous Methods
    SEARCH_REFERENCE_POSITION = "com.attocube.amc.control.searchReferencePosition"
    GET_DEVICE_TYPE = "com.attocube.amc.description.getDeviceType"
